name: noraynapp
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.3
  provider: ^4.0.5+1
  carousel_slider: ^2.0.0
  firebase_core: ^0.4.4+3
  cloud_firestore: ^0.13.5
  firebase_storage: ^3.1.5
  curved_navigation_bar: ^0.3.2
  url_launcher: ^5.4.5
  font_awesome_flutter: ^8.8.1
#  easy_localization: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
     - assets/ar.json
     - assets/en.json
     - images/
#     - images/a_dot_ham.jpeg
#   fonts:
#     - family: Schyler
#       fonts:
#         - asset: fonts/Schyler-Regular.ttf
#         - asset: fonts/Schyler-Italic.ttf
#           style: italic
